language: python

python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
  - 3.3
  - 3.4

install:
  - python -c 'import setup; print(setup.REQUIRES_PIP)' |xargs pip install
  - pip install robpol86-codecov docopt
  - pip install .

script:
  - python setup.py test
  - python example.py print

after_success: codecov
