environment:
  CODECOV_TOKEN:
    secure: rKevzGfmt4DqixpPWYf8KE40q2a4NknSXJiecG663Raa/AJXC1r6kdfEoiqiCQRe
  PYTHONIOENCODING: utf-8

  matrix:
    - PYTHON: C:\Python27
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python32
    - PYTHON: C:\Python32-x64
    - PYTHON: C:\Python33
    - PYTHON: C:\Python33-x64
    - PYTHON: C:\Python34
    - PYTHON: C:\Python34-x64

init:
  - IF DEFINED PYTHON set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
  - ps: Start-FileDownload https://raw.github.com/pypa/pip/master/contrib/get-pip.py
  - python get-pip.py
  - ps: pip install $(python -c 'import setup; print(setup.REQUIRES_PIP)')
  - pip install robpol86-codecov docopt

build_script:
  - ps: mv .git ..
  - pip install .
  - ps: mv ..\.git .

test_script:
  - python setup.py test
  - python example.py print

after_test: codecov
